spring.application.name=TulumCore

spring.datasource.url=jdbc:postgresql://ep-damp-butterfly-adugaoou-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_dqbQwm7LBn2j
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.tenant_identifier_resolver=com.tulumcore.api.config.TenantIdentifierResolver
spring.jpa.open-in-view=false

# Credenciales de Cloudinary
cloudinary.cloud_name=dfseodfjv
cloudinary.api_key=398243517695549
cloudinary.api_secret=tZ7ZYbQMmzVKDlti0ED42FNUjPo

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB