spring.application.name=TulumCore
spring.config.import=optional:file:.env[.properties]
server.port=${PORT:8080}

# =============================================
# CORS
# =============================================
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:https://tulum-core.netlify.app,https://teal-tanuki-dea827.netlify.app,http://localhost:3000,http://localhost:5173}

# =============================================
# BASE DE DATOS
# =============================================
spring.datasource.url=jdbc:postgresql://ep-odd-cherry-ancfqxzd-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_dzJHyEe1g5vV
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.tenant_identifier_resolver=com.tulumcore.api.config.TenantIdentifierResolver
spring.jpa.open-in-view=false

# =============================================
# CLOUDINARY
# =============================================
cloudinary.cloud_name=dfseodfjv
cloudinary.api_key=398243517695549
cloudinary.api_secret=tZ7ZYbQMmzVKDlti0ED42FNUjPo

# =============================================
# JWT
# =============================================
jwt.secret=4365d202cdd365de04e429fec5b450931a3ba86a1275f31cecc8dcf3d7eb903f
jwt.expiration-ms=86400000

# =============================================
# UPLOADS
# =============================================
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
